name: Publish addon

on:
  push:
    tags:
      - '*'
      - '!*-beta'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -q Pylint Kodistubs typing-extensions
    - name: Check with Pylint
      run: |
        pylint --exit-zero metadata.tvmaze/libs metadata.tvmaze/main.py
    - name: Install addon checker
      run: |
        pip install -q kodi-addon-checker
    - name: Check with addon-checker
      run: |
        kodi-addon-checker --branch matrix
    - name: Install addon submitter
      run: |
        pip install -q git+https://github.com/xbmc/kodi-addon-submitter.git
    - name: Submit addon
      run: |
        submit-addon -r repo-scrapers -b matrix -s --pull-request metadata.tvmaze
      env:
        GH_USERNAME: romanvm
        GH_TOKEN: ${{ secrets.gh_token }}
        EMAIL: roman1972@gmail.com
